export const AppRoutes = {
  home: "/",
  about: "/about",
  products: "/products",
  productClothes: "/products/clothes",
  productFurniture: "/products/furniture",
  productShoes: "/products/shoes",
  productElectronics: "/products/electronics",
  productOthers: "/products/others",
  blog: "/blog",
  cart: "/account/cart",
  checkout: "/account/checkout",
  account: "/account",
  contact: "/contact",
  login: "/login",
  register: "/register",
  forgotPassword: "/login",
};
